### ISSUE TITLE
Where can I get the dataset? The official LANL dataset does not satisfy the code

### ISSUE THREAD

**Issue by Meoooww** [quanghuy17111999/LMTracker#3]
the lanl dataset can be found in https://csr.lanl.gov/data/auth/
it contains:
![image](https://github.com/quanghuy17111999/LMTracker/assets/56733007/0a7a9899-ae59-4ab6-956d-ce575b306636)

However, these data mentioned in graph_construction.py are not included：
![image](https://github.com/quanghuy17111999/LMTracker/assets/56733007/1f62d1e7-bc1b-423e-826f-a2ea3fe8a83e)
![image](https://github.com/quanghuy17111999/LMTracker/assets/56733007/20e14c2e-5523-481e-b369-b5d592a5775b)

where should i download these data?

**Comment by huyqngo** [comment]
Hi, 

The data should be available here: https://csr.lanl.gov/data/cyber1/. 
We use LANL Comprehensive, Multi-Source Cyber-Security Events data. 

Best regards, 
Huy

**Comment by Meoooww** [comment]
> Hi,
> 
> The data should be available here: https://csr.lanl.gov/data/cyber1/. We use LANL Comprehensive, Multi-Source Cyber-Security Events data.
> 
> Best regards, Huy

thx!

**Comment by huyqngo** [comment]
No worries. 
You might have to run extract_redteam_auth.ipynb to preprocess and get 2 files red_team_list.pkl and redteam_auth.txt
